library(dplyr)
Mecha_table <- read.csv(file='MechaCar_mpg.csv', check.names = F,stringsAsFactors = F)
mpg_mod <- lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD,data=Mecha_table) 
View(mpg_mod)
mpg_mod_summary <- summary(lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD,data=Mecha_table))
View(mpg_mod_summary)
